version: '3.7'
services:
  bm-boot:
    container_name: bmboot
    restart: always
    hostname: booksmanager-boot
    build: ./bm-boot
    image: bm/boot:1.0
    expose:
      - 8080
    ports:
      - ${DOCKER_IP:127.0.0.1}:8081:8080
    environment:
      SPRING_PROFILES_ACTIVE: postgres
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - postgres
    networks:
      - bm-network

  bm-tomcat:
    container_name: bmtomcat
    restart: always
    hostname: booksmanager-tomcat
    build: ./bm-tomcat
    image: bm/tomcat:9.0.20-jre8-alpine
    environment:
      SPRING_PROFILES_ACTIVE: war
    expose:
      - 8080
    ports:
      - ${DOCKER_IP:127.0.0.1}:8082:8080
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - postgres
    networks:
      - bm-network

  admin-server:
    container_name: admin-server
    restart: always
    hostname: admin-server
    build: ./admin-server
    image: bm/admin-server:1.0
    expose:
      - 8080
    ports:
      - ${DOCKER_IP:127.0.0.1}:8083:8080
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    networks:
      - docker-network

  postgres:
    container_name: postgres-bm
    restart: always
    build: ./postgres
    image: bm/postgres:9.6.12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD='postgres'
    expose:
      - 5432
    ports:
      - ${DOCKER_IP:127.0.0.1}:5432:5432
    networks:
      - bm-network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    #volumes:
    #  - postgres-volume:/var/lib/postgresql/data
      #- postgres-initdb-volume:/docker-entrypoint-initdb.d

  keycloak:
    container_name: keycloak-bm
    restart: always
    image: jboss/keycloak:6.0.1
    expose:
      - 8080
    ports:
      - ${DOCKER_IP:127.0.0.1}:8084:8080
    volumes:
      - keycloak-data-volume:/keycloak/standalone/data
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SCHEMA: public
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    networks:
      - docker-network
    depends_on:
      - postgres

networks:
  bm-network:
    driver: bridge

#volumes:
  #postgres-volume:
    #external: true
  #keycloak-data-volume:
    #external: true
